export interface CountryCode {
  name: string;
  code: string;
  dialCode: string;
  flag: string;
  maxLength: number;
}

export const countryCodes: CountryCode[] = [
  { name: 'India', code: 'IN', dialCode: '+91', flag: '🇮🇳', maxLength: 10 },
  { name: 'United States', code: 'US', dialCode: '+1', flag: '🇺🇸', maxLength: 10 },
  { name: 'United Kingdom', code: 'GB', dialCode: '+44', flag: '🇬🇧', maxLength: 10 },
  { name: 'Canada', code: 'CA', dialCode: '+1', flag: '🇨🇦', maxLength: 10 },
  { name: 'Australia', code: 'AU', dialCode: '+61', flag: '🇦🇺', maxLength: 9 },
  { name: 'Germany', code: 'DE', dialCode: '+49', flag: '🇩🇪', maxLength: 11 },
  { name: 'France', code: 'FR', dialCode: '+33', flag: '🇫🇷', maxLength: 10 },
  { name: 'Japan', code: 'JP', dialCode: '+81', flag: '🇯🇵', maxLength: 11 },
  { name: 'China', code: 'CN', dialCode: '+86', flag: '🇨🇳', maxLength: 11 },
  { name: 'South Korea', code: 'KR', dialCode: '+82', flag: '🇰🇷', maxLength: 11 },
  { name: 'Singapore', code: 'SG', dialCode: '+65', flag: '🇸🇬', maxLength: 8 },
  { name: 'United Arab Emirates', code: 'AE', dialCode: '+971', flag: '🇦🇪', maxLength: 9 },
  { name: 'Saudi Arabia', code: 'SA', dialCode: '+966', flag: '🇸🇦', maxLength: 9 },
  { name: 'Qatar', code: 'QA', dialCode: '+974', flag: '🇶🇦', maxLength: 8 },
  { name: 'Kuwait', code: 'KW', dialCode: '+965', flag: '🇰🇼', maxLength: 8 },
  { name: 'Bahrain', code: 'BH', dialCode: '+973', flag: '🇧🇭', maxLength: 8 },
  { name: 'Oman', code: 'OM', dialCode: '+968', flag: '🇴🇲', maxLength: 8 },
  { name: 'Malaysia', code: 'MY', dialCode: '+60', flag: '🇲🇾', maxLength: 10 },
  { name: 'Thailand', code: 'TH', dialCode: '+66', flag: '🇹🇭', maxLength: 9 },
  { name: 'Indonesia', code: 'ID', dialCode: '+62', flag: '🇮🇩', maxLength: 11 },
  { name: 'Philippines', code: 'PH', dialCode: '+63', flag: '🇵🇭', maxLength: 10 },
  { name: 'Vietnam', code: 'VN', dialCode: '+84', flag: '🇻🇳', maxLength: 9 },
  { name: 'Bangladesh', code: 'BD', dialCode: '+880', flag: '🇧🇩', maxLength: 10 },
  { name: 'Pakistan', code: 'PK', dialCode: '+92', flag: '🇵🇰', maxLength: 10 },
  { name: 'Sri Lanka', code: 'LK', dialCode: '+94', flag: '🇱🇰', maxLength: 9 },
  { name: 'Nepal', code: 'NP', dialCode: '+977', flag: '🇳🇵', maxLength: 10 },
  { name: 'Bhutan', code: 'BT', dialCode: '+975', flag: '🇧🇹', maxLength: 8 },
  { name: 'Maldives', code: 'MV', dialCode: '+960', flag: '🇲🇻', maxLength: 7 },
  { name: 'Afghanistan', code: 'AF', dialCode: '+93', flag: '🇦🇫', maxLength: 9 },
  { name: 'Myanmar', code: 'MM', dialCode: '+95', flag: '🇲🇲', maxLength: 9 },
  { name: 'Cambodia', code: 'KH', dialCode: '+855', flag: '🇰🇭', maxLength: 9 },
  { name: 'Laos', code: 'LA', dialCode: '+856', flag: '🇱🇦', maxLength: 8 },
  { name: 'Brunei', code: 'BN', dialCode: '+673', flag: '🇧🇳', maxLength: 7 },
  { name: 'Timor-Leste', code: 'TL', dialCode: '+670', flag: '🇹🇱', maxLength: 8 },
  { name: 'Italy', code: 'IT', dialCode: '+39', flag: '🇮🇹', maxLength: 10 },
  { name: 'Spain', code: 'ES', dialCode: '+34', flag: '🇪🇸', maxLength: 9 },
  { name: 'Netherlands', code: 'NL', dialCode: '+31', flag: '🇳🇱', maxLength: 9 },
  { name: 'Belgium', code: 'BE', dialCode: '+32', flag: '🇧🇪', maxLength: 9 },
  { name: 'Switzerland', code: 'CH', dialCode: '+41', flag: '🇨🇭', maxLength: 9 },
  { name: 'Austria', code: 'AT', dialCode: '+43', flag: '🇦🇹', maxLength: 10 },
  { name: 'Sweden', code: 'SE', dialCode: '+46', flag: '🇸🇪', maxLength: 9 },
  { name: 'Norway', code: 'NO', dialCode: '+47', flag: '🇳🇴', maxLength: 8 },
  { name: 'Denmark', code: 'DK', dialCode: '+45', flag: '🇩🇰', maxLength: 8 },
  { name: 'Finland', code: 'FI', dialCode: '+358', flag: '🇫🇮', maxLength: 9 },
  { name: 'Poland', code: 'PL', dialCode: '+48', flag: '🇵🇱', maxLength: 9 },
  { name: 'Czech Republic', code: 'CZ', dialCode: '+420', flag: '🇨🇿', maxLength: 9 },
  { name: 'Hungary', code: 'HU', dialCode: '+36', flag: '🇭🇺', maxLength: 9 },
  { name: 'Romania', code: 'RO', dialCode: '+40', flag: '🇷🇴', maxLength: 9 },
  { name: 'Bulgaria', code: 'BG', dialCode: '+359', flag: '🇧🇬', maxLength: 9 },
  { name: 'Croatia', code: 'HR', dialCode: '+385', flag: '🇭🇷', maxLength: 9 },
  { name: 'Slovenia', code: 'SI', dialCode: '+386', flag: '🇸🇮', maxLength: 8 },
  { name: 'Slovakia', code: 'SK', dialCode: '+421', flag: '🇸🇰', maxLength: 9 },
  { name: 'Estonia', code: 'EE', dialCode: '+372', flag: '🇪🇪', maxLength: 8 },
  { name: 'Latvia', code: 'LV', dialCode: '+371', flag: '🇱🇻', maxLength: 8 },
  { name: 'Lithuania', code: 'LT', dialCode: '+370', flag: '🇱🇹', maxLength: 8 },
  { name: 'Russia', code: 'RU', dialCode: '+7', flag: '🇷🇺', maxLength: 10 },
  { name: 'Ukraine', code: 'UA', dialCode: '+380', flag: '🇺🇦', maxLength: 9 },
  { name: 'Belarus', code: 'BY', dialCode: '+375', flag: '🇧🇾', maxLength: 9 },
  { name: 'Moldova', code: 'MD', dialCode: '+373', flag: '🇲🇩', maxLength: 8 },
  { name: 'Georgia', code: 'GE', dialCode: '+995', flag: '🇬🇪', maxLength: 9 },
  { name: 'Armenia', code: 'AM', dialCode: '+374', flag: '🇦🇲', maxLength: 8 },
  { name: 'Azerbaijan', code: 'AZ', dialCode: '+994', flag: '🇦🇿', maxLength: 9 },
  { name: 'Kazakhstan', code: 'KZ', dialCode: '+7', flag: '🇰🇿', maxLength: 10 },
  { name: 'Uzbekistan', code: 'UZ', dialCode: '+998', flag: '🇺🇿', maxLength: 9 },
  { name: 'Kyrgyzstan', code: 'KG', dialCode: '+996', flag: '🇰🇬', maxLength: 9 },
  { name: 'Tajikistan', code: 'TJ', dialCode: '+992', flag: '🇹🇯', maxLength: 9 },
  { name: 'Turkmenistan', code: 'TM', dialCode: '+993', flag: '🇹🇲', maxLength: 8 },
  { name: 'Mongolia', code: 'MN', dialCode: '+976', flag: '🇲🇳', maxLength: 8 },
  { name: 'Brazil', code: 'BR', dialCode: '+55', flag: '🇧🇷', maxLength: 11 },
  { name: 'Argentina', code: 'AR', dialCode: '+54', flag: '🇦🇷', maxLength: 10 },
  { name: 'Chile', code: 'CL', dialCode: '+56', flag: '🇨🇱', maxLength: 9 },
  { name: 'Colombia', code: 'CO', dialCode: '+57', flag: '🇨🇴', maxLength: 10 },
  { name: 'Peru', code: 'PE', dialCode: '+51', flag: '🇵🇪', maxLength: 9 },
  { name: 'Venezuela', code: 'VE', dialCode: '+58', flag: '🇻🇪', maxLength: 10 },
  { name: 'Ecuador', code: 'EC', dialCode: '+593', flag: '🇪🇨', maxLength: 9 },
  { name: 'Bolivia', code: 'BO', dialCode: '+591', flag: '🇧🇴', maxLength: 8 },
  { name: 'Paraguay', code: 'PY', dialCode: '+595', flag: '🇵🇾', maxLength: 9 },
  { name: 'Uruguay', code: 'UY', dialCode: '+598', flag: '🇺🇾', maxLength: 8 },
  { name: 'Guyana', code: 'GY', dialCode: '+592', flag: '🇬🇾', maxLength: 7 },
  { name: 'Suriname', code: 'SR', dialCode: '+597', flag: '🇸🇷', maxLength: 7 },
  { name: 'South Africa', code: 'ZA', dialCode: '+27', flag: '🇿🇦', maxLength: 9 },
  { name: 'Nigeria', code: 'NG', dialCode: '+234', flag: '🇳🇬', maxLength: 10 },
  { name: 'Kenya', code: 'KE', dialCode: '+254', flag: '🇰🇪', maxLength: 9 },
  { name: 'Ghana', code: 'GH', dialCode: '+233', flag: '🇬🇭', maxLength: 9 },
  { name: 'Ethiopia', code: 'ET', dialCode: '+251', flag: '🇪🇹', maxLength: 9 },
  { name: 'Tanzania', code: 'TZ', dialCode: '+255', flag: '🇹🇿', maxLength: 9 },
  { name: 'Uganda', code: 'UG', dialCode: '+256', flag: '🇺🇬', maxLength: 9 },
  { name: 'Morocco', code: 'MA', dialCode: '+212', flag: '🇲🇦', maxLength: 9 },
  { name: 'Algeria', code: 'DZ', dialCode: '+213', flag: '🇩🇿', maxLength: 9 },
  { name: 'Tunisia', code: 'TN', dialCode: '+216', flag: '🇹🇳', maxLength: 8 },
  { name: 'Libya', code: 'LY', dialCode: '+218', flag: '🇱🇾', maxLength: 9 },
  { name: 'Egypt', code: 'EG', dialCode: '+20', flag: '🇪🇬', maxLength: 10 },
  { name: 'Sudan', code: 'SD', dialCode: '+249', flag: '🇸🇩', maxLength: 9 },
  { name: 'Somalia', code: 'SO', dialCode: '+252', flag: '🇸🇴', maxLength: 9 },
  { name: 'Djibouti', code: 'DJ', dialCode: '+253', flag: '🇩🇯', maxLength: 8 },
  { name: 'Eritrea', code: 'ER', dialCode: '+291', flag: '🇪🇷', maxLength: 7 },
  { name: 'Israel', code: 'IL', dialCode: '+972', flag: '🇮🇱', maxLength: 9 },
  { name: 'Palestine', code: 'PS', dialCode: '+970', flag: '🇵🇸', maxLength: 9 },
  { name: 'Jordan', code: 'JO', dialCode: '+962', flag: '🇯🇴', maxLength: 9 },
  { name: 'Lebanon', code: 'LB', dialCode: '+961', flag: '🇱🇧', maxLength: 8 },
  { name: 'Syria', code: 'SY', dialCode: '+963', flag: '🇸🇾', maxLength: 9 },
  { name: 'Iraq', code: 'IQ', dialCode: '+964', flag: '🇮🇶', maxLength: 10 },
  { name: 'Iran', code: 'IR', dialCode: '+98', flag: '🇮🇷', maxLength: 10 },
  { name: 'Turkey', code: 'TR', dialCode: '+90', flag: '🇹🇷', maxLength: 10 },
  { name: 'Cyprus', code: 'CY', dialCode: '+357', flag: '🇨🇾', maxLength: 8 },
  { name: 'Greece', code: 'GR', dialCode: '+30', flag: '🇬🇷', maxLength: 10 },
  { name: 'Albania', code: 'AL', dialCode: '+355', flag: '🇦🇱', maxLength: 9 },
  { name: 'Macedonia', code: 'MK', dialCode: '+389', flag: '🇲🇰', maxLength: 8 },
  { name: 'Montenegro', code: 'ME', dialCode: '+382', flag: '🇲🇪', maxLength: 8 },
  { name: 'Serbia', code: 'RS', dialCode: '+381', flag: '🇷🇸', maxLength: 9 },
  { name: 'Bosnia and Herzegovina', code: 'BA', dialCode: '+387', flag: '🇧🇦', maxLength: 8 },
  { name: 'Kosovo', code: 'XK', dialCode: '+383', flag: '🇽🇰', maxLength: 8 },
  { name: 'Malta', code: 'MT', dialCode: '+356', flag: '🇲🇹', maxLength: 8 },
  { name: 'Iceland', code: 'IS', dialCode: '+354', flag: '🇮🇸', maxLength: 7 },
  { name: 'Ireland', code: 'IE', dialCode: '+353', flag: '🇮🇪', maxLength: 9 },
  { name: 'Portugal', code: 'PT', dialCode: '+351', flag: '🇵🇹', maxLength: 9 },
  { name: 'Luxembourg', code: 'LU', dialCode: '+352', flag: '🇱🇺', maxLength: 9 },
  { name: 'Monaco', code: 'MC', dialCode: '+377', flag: '🇲🇨', maxLength: 8 },
  { name: 'Andorra', code: 'AD', dialCode: '+376', flag: '🇦🇩', maxLength: 6 },
  { name: 'San Marino', code: 'SM', dialCode: '+378', flag: '🇸🇲', maxLength: 10 },
  { name: 'Vatican City', code: 'VA', dialCode: '+379', flag: '🇻🇦', maxLength: 10 },
  { name: 'Liechtenstein', code: 'LI', dialCode: '+423', flag: '🇱🇮', maxLength: 7 },
  { name: 'New Zealand', code: 'NZ', dialCode: '+64', flag: '🇳🇿', maxLength: 9 },
  { name: 'Fiji', code: 'FJ', dialCode: '+679', flag: '🇫🇯', maxLength: 7 },
  { name: 'Papua New Guinea', code: 'PG', dialCode: '+675', flag: '🇵🇬', maxLength: 8 },
  { name: 'Solomon Islands', code: 'SB', dialCode: '+677', flag: '🇸🇧', maxLength: 7 },
  { name: 'Vanuatu', code: 'VU', dialCode: '+678', flag: '🇻🇺', maxLength: 7 },
  { name: 'New Caledonia', code: 'NC', dialCode: '+687', flag: '🇳🇨', maxLength: 6 },
  { name: 'French Polynesia', code: 'PF', dialCode: '+689', flag: '🇵🇫', maxLength: 8 },
  { name: 'Samoa', code: 'WS', dialCode: '+685', flag: '🇼🇸', maxLength: 7 },
  { name: 'Tonga', code: 'TO', dialCode: '+676', flag: '🇹🇴', maxLength: 7 },
  { name: 'Kiribati', code: 'KI', dialCode: '+686', flag: '🇰🇮', maxLength: 5 },
  { name: 'Tuvalu', code: 'TV', dialCode: '+688', flag: '🇹🇻', maxLength: 6 },
  { name: 'Nauru', code: 'NR', dialCode: '+674', flag: '🇳🇷', maxLength: 7 },
  { name: 'Palau', code: 'PW', dialCode: '+680', flag: '🇵🇼', maxLength: 7 },
  { name: 'Marshall Islands', code: 'MH', dialCode: '+692', flag: '🇲🇭', maxLength: 7 },
  { name: 'Micronesia', code: 'FM', dialCode: '+691', flag: '🇫🇲', maxLength: 7 },
  { name: 'Cook Islands', code: 'CK', dialCode: '+682', flag: '🇨🇰', maxLength: 5 },
  { name: 'Niue', code: 'NU', dialCode: '+683', flag: '🇳🇺', maxLength: 4 },
  { name: 'Tokelau', code: 'TK', dialCode: '+690', flag: '🇹🇰', maxLength: 4 },
  { name: 'American Samoa', code: 'AS', dialCode: '+1', flag: '🇦🇸', maxLength: 10 },
  { name: 'Guam', code: 'GU', dialCode: '+1', flag: '🇬🇺', maxLength: 10 },
  { name: 'Northern Mariana Islands', code: 'MP', dialCode: '+1', flag: '🇲🇵', maxLength: 10 },
  { name: 'Puerto Rico', code: 'PR', dialCode: '+1', flag: '🇵🇷', maxLength: 10 },
  { name: 'US Virgin Islands', code: 'VI', dialCode: '+1', flag: '🇻🇮', maxLength: 10 },
  { name: 'British Virgin Islands', code: 'VG', dialCode: '+1', flag: '🇻🇬', maxLength: 10 },
  { name: 'Anguilla', code: 'AI', dialCode: '+1', flag: '🇦🇮', maxLength: 10 },
  { name: 'Antigua and Barbuda', code: 'AG', dialCode: '+1', flag: '🇦🇬', maxLength: 10 },
  { name: 'Aruba', code: 'AW', dialCode: '+297', flag: '🇦🇼', maxLength: 7 },
  { name: 'Bahamas', code: 'BS', dialCode: '+1', flag: '🇧🇸', maxLength: 10 },
  { name: 'Barbados', code: 'BB', dialCode: '+1', flag: '🇧🇧', maxLength: 10 },
  { name: 'Belize', code: 'BZ', dialCode: '+501', flag: '🇧🇿', maxLength: 7 },
  { name: 'Bermuda', code: 'BM', dialCode: '+1', flag: '🇧🇲', maxLength: 10 },
  { name: 'Cayman Islands', code: 'KY', dialCode: '+1', flag: '🇰🇾', maxLength: 10 },
  { name: 'Costa Rica', code: 'CR', dialCode: '+506', flag: '🇨🇷', maxLength: 8 },
  { name: 'Cuba', code: 'CU', dialCode: '+53', flag: '🇨🇺', maxLength: 8 },
  { name: 'Curaçao', code: 'CW', dialCode: '+599', flag: '🇨🇼', maxLength: 7 },
  { name: 'Dominica', code: 'DM', dialCode: '+1', flag: '🇩🇲', maxLength: 10 },
  { name: 'Dominican Republic', code: 'DO', dialCode: '+1', flag: '🇩🇴', maxLength: 10 },
  { name: 'El Salvador', code: 'SV', dialCode: '+503', flag: '🇸🇻', maxLength: 8 },
  { name: 'Grenada', code: 'GD', dialCode: '+1', flag: '🇬🇩', maxLength: 10 },
  { name: 'Guatemala', code: 'GT', dialCode: '+502', flag: '🇬🇹', maxLength: 8 },
  { name: 'Haiti', code: 'HT', dialCode: '+509', flag: '🇭🇹', maxLength: 8 },
  { name: 'Honduras', code: 'HN', dialCode: '+504', flag: '🇭🇳', maxLength: 8 },
  { name: 'Jamaica', code: 'JM', dialCode: '+1', flag: '🇯🇲', maxLength: 10 },
  { name: 'Mexico', code: 'MX', dialCode: '+52', flag: '🇲🇽', maxLength: 10 },
  { name: 'Nicaragua', code: 'NI', dialCode: '+505', flag: '🇳🇮', maxLength: 8 },
  { name: 'Panama', code: 'PA', dialCode: '+507', flag: '🇵🇦', maxLength: 8 },
  { name: 'Saint Kitts and Nevis', code: 'KN', dialCode: '+1', flag: '🇰🇳', maxLength: 10 },
  { name: 'Saint Lucia', code: 'LC', dialCode: '+1', flag: '🇱🇨', maxLength: 10 },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', dialCode: '+1', flag: '🇻🇨', maxLength: 10 },
  { name: 'Sint Maarten', code: 'SX', dialCode: '+1', flag: '🇸🇽', maxLength: 10 },
  { name: 'Trinidad and Tobago', code: 'TT', dialCode: '+1', flag: '🇹🇹', maxLength: 10 },
  { name: 'Turks and Caicos Islands', code: 'TC', dialCode: '+1', flag: '🇹🇨', maxLength: 10 }
];

function uniqueByCountryCode(list: CountryCode[]): CountryCode[] {
  const seen = new Set<string>();
  const unique: CountryCode[] = [];
  for (const country of list) {
    if (seen.has(country.code)) continue;
    seen.add(country.code);
    unique.push(country);
  }
  return unique;
}

export const uniqueCountryCodes = uniqueByCountryCode(countryCodes);
