/**
 * Generated by scripts/ensure-build.mjs — Hostinger entry (do not edit by hand).
 * Binds process.env.PORT immediately, then mounts dist/server.js Express app.
 */
'use strict';

const http = require('http');
const path = require('path');
const fs = require('fs');

const PORT = Number(process.env.PORT) || 3000;
const boot = { phase: 'booting', error: null, ready: false };
let expressApp = null;

const server = http.createServer((req, res) => {
  if (expressApp) {
    expressApp(req, res);
    return;
  }
  const url = (req.url || '/').split('?')[0];
  if (url === '/health' || url === '/') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      ok: true,
      service: 'visitor-analytics',
      phase: boot.phase,
      ready: boot.ready,
      error: boot.error,
      time: new Date().toISOString(),
    }));
    return;
  }
  res.writeHead(503, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({
    error: 'Application still starting',
    phase: boot.phase,
    detail: boot.error,
  }));
});

server.listen(PORT, '0.0.0.0', () => {
  console.log('[visitor-analytics] app.js listening on 0.0.0.0:' + PORT);
  boot.phase = 'loading-dist';
  const entry = path.join(__dirname, 'dist', 'server.js');
  if (!fs.existsSync(entry)) {
    boot.phase = 'missing-dist';
    boot.error = 'dist/server.js not found — run npm run build';
    console.error('[visitor-analytics]', boot.error);
    return;
  }
  try {
    process.env.VA_AUTOSTART = '0';
    const mod = require(entry);
    if (!mod.app) throw new Error('dist/server.js did not export app');
    if (mod.realtimeHub && typeof mod.realtimeHub.attach === 'function') {
      mod.realtimeHub.attach(server);
    }
    expressApp = mod.app;
    boot.ready = true;
    boot.phase = 'ready';
    console.log('[visitor-analytics] Express app mounted');
    if (mod.pool && typeof mod.pool.query === 'function') {
      mod.pool.query('SELECT 1')
        .then(function () { console.log('[visitor-analytics] database connection OK'); })
        .catch(function (err) {
          var msg = err && err.message ? err.message : String(err);
          console.error('[visitor-analytics] database not ready:', msg);
          if (/Access denied/i.test(msg)) {
            console.error('[visitor-analytics] Hostinger tip: set DB_HOST to Remote MySQL hostname from hPanel (not 127.0.0.1), allow Any Host (%), set DB_PASSWORD, Redeploy.');
          }
        });
    }
  } catch (err) {
    boot.phase = 'load-failed';
    boot.error = err && err.stack ? String(err.stack) : String(err);
    console.error('[visitor-analytics] failed to load dist/server.js', err);
  }
});

process.on('SIGINT', function () { process.exit(0); });
process.on('SIGTERM', function () { process.exit(0); });
